### ISSUE TITLE
Git (hub) style is missing. - a bit maintenance required

### ISSUE THREAD

**Issue by DanielRamp** [RPiList/specials#3]
This Repository doesn't have **Repository Details** like a `README.md`, a title and link and a `LICENSE`.

I @DanielRamp might add the details from the file `notserious` itself.

## Todo list:
- [x] `README.md` #4 (waiting to merge)
- [x] merge other pull requests (be active!) like these updates #1 #2 #5 
- [ ] title, link and topics
- [ ] LICENCE

- [ ] "englishing" (new, from @ZeroDot1)

**Comment by ZeroDot1** [comment]
Hi @RPiList,

All texts should be written in English, this is very important, because it is a blacklist which is very interesting internationally.

The list should be sorted alphabetically 0-9 a-ü and so on.
There should also be a hosts version of the list.
Example:
```js
0.0.0.0 domain.xyz
0.0.0.0 xyztest.site
0.0.0.0 evil-hackers-are-evil.com
0.0.0.0 sempervideo-babbling-too-much-about-porn.ru
0.0.0.0 this-is-a-totally-crazy-example.cf
```
The project should have an easy to remember name.
The files should also have the matching file extension, e.g. if they are just text.

At the moment the project looks like it was done by a child in preschool.
Please change that, after that you should drink a tea to relax.

@RPiList Have a nice day!

**Comment by RPiList** [comment]
> All texts should be written in English, this is very important, because it is a blacklist which is very interesting internationally.

Not sure about the "interessting internationally". Target audience is german speaking, since almost all URL are fraudulent webshops using german language. English speaking users will not fall for that. :-)

> 
> The list should be sorted alphabetically 0-9 a-ü and so on.

I agree, but maintaining the list is so much easier when it's not sorted. Will do in a later update.

> There should also be a hosts version of the list.
> Example:
> 
> 0.0.0.0 evil-hackers-are-evil.com

A host version is not yet planned. It is only supposed to be a blocklist for pi-hole.net. Pi-Hole does not need an IP-prefix in front of every URL.

> The project should have an easy to remember name.

Nobody needs to remember the project name. It's just a small project, only referenced in a (few) video(s). Since they can't be changed, changing the name (and URL I guess) will mean the links in the video will not work any longer.

> At the moment the project looks like it was done by a child in preschool.

Yeah... it pretty much is. But, as long as it get's the job done...

**Comment by ZeroDot1** [comment]
Hi @RPiList,

> I agree, but maintaining the list is so much easier when it's not sorted. Will do in a later update.

Please use the following script for automatic sorting: 
```bash
#!/bin/bash
# Automatic cleaning script created by: https://twitter.com/zero_dot1?lang=de
# Contact: zerodot1@bk.ru
cd 'RPiList/specials/'
clear
echo "Automatic cleaning script created by: https://twitter.com/zero_dot1?lang=de"
# Delete duplicate entries:
sort -u 'notserious' | sort -u >> 'tmp.txt'
# Delete the old file:
rm -rf 'notserious'
# Create a new file by simply copying it:
cp 'tmp.txt' 'notserious'
# Delete the garbage:
rm -rf 'tmp.txt'
# The result is a sorted file

```

**Comment by McModknower** [comment]
@ZeroDot1 
Why don't you use the mv command at the end of your script?
> ```
> # Create a new file by simply copying it:
> cp 'tmp.txt' 'notserious'
> # Delete the garbage:
> rm -rf 'tmp.txt'
> # The result is a sorted file
> ```
